### PR TITLE
Added windows-specific setup notes

### PR DESCRIPTION
**Pull request by yugensoft**
These tweaks are required to get a development instance up and running on windows
Pursuant to https://status-im.slack.com/archives/C3NFZKNRG/p1494009635732517

### CODE REVIEW

**Comment by Smokyish** [comment]
I'll request a couple of clarifications and fixes.

Why do we suddenly need to install Ruby for OSX?

You added `brew install ruby` and Homebrew is mentioned as a requirement for OSX and there is no mention that this would be Windows specific and wouldn't this be done using `choco` if it's only required for Windows?

Is Cygwin required for Windows or can this all be done via Command Prompt, since there is no mention of Cygwin in the requirements?

**Comment by yugensoft** [comment]
Ruby is needed for the subsequent `gem` install. Well should I change it to a grid-like style then, with dependency on left and then mac-windows-linux install instructions one after the other? Or split it to a different section for each OS? For instance, the installation on linux is quite different too

**Comment by Smokyish** [comment]
There is work underway to redo the build guide and changing the style isn't in the scope of this PR and should thus go to another PR.

>Ruby is needed for the subsequent gem install.  

So it's unclear to me why you used `brew` on the install?

You could just add that something is just required for building on Windows like Homebrew is for OSX, ie. 

Ruby `choco install ruby` (optional, for Windows)

**Comment by yugensoft** [comment]
OK changed.
On cygwin, cmd, I don't know, I only have the information on where you shouldn't use it. My guess is most windows developers have Cygwin since one can barely function without it. That's all I have, I can't commit to trying the whole build setup again.

**Comment by Smokyish** [comment]
Thank you for your contribution @yugensoft!

**Comment by yugensoft** [comment]
It seems to have broken, it's not rendering right on the webpage like it is in the preview. I'll try building it myself and see what's going wrong

**Comment by yugensoft** [comment]
ok it was just a missing newline

**Pull request merged**
